name: Gatsby Build Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.PROJECT_416_SECRET }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          skip-publish: true
